on:
  pull_request:
    branches: [ main, review ]

  push:
    branches: [ main, dev, review ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.12.3
        id: todo